import run
story_dict = {
    "game_intro": ["Welcome to an interactive story-based game. It was \n",
                   "inspired by a popular TV Show 'Once Upon a Time'. \n",
                   "Please choose from the following options. \n",
                   "1. Read instructions",
                   "2. Go to the story\n"],
    "game_instructions": ["When you start the game, you will need to enter \n",
                          "your name and gender. This will customise the \n",
                          "game play. Once inside the story, you will be \n",
                          "prompted to choose between two options to see \n",
                          "the outcome of the game. Enter your preferred \n",
                          "option and see if you win!\n\n"
                          "Enjoy, and good luck!\n"],
    "story_intro": ["Once upon a time in a far away land, there lived Snow\n",
                    "White with her prince charming. After defeating the \n",
                    "Evil Queen, peace was brought to their Kingdom. Snow \n",
                    "White and Prince Charming were happily expecting an \n",
                    "addition to their family - a little baby \n",
                    f"called {user}.\n\n",
                    "Alas, their joy was shortlived. The Evil Queen \n",
                    "announced she was brewing a curse. The curse that \n",
                    "would trap the kingdom in her fantasy world in \n",
                    "a far away land. A city called StoryBrooke, in Maine, \n",
                    "USA… where all fairytale characters would be trapped \n",
                    "in unhappy stories, clueless of who they really are. \n",
                    "Worried about the hapless future, Snow and Charming \n",
                    "set out to stop the Evil Queen.\n"],
    "chapter1": ["Chapter 1\n",
                 "They searched for solutions and ways to stop her.\n",
                 "Rumours reached them that Rumpelstiltskin to help, \n",
                 "would be able however, Snow was aware of his 'deals'\n",
                 "and was cautious to approach him. \n",
                 "Should Snow and Charming:\n\n",
                 "1. Confront the Queen.\n",
                 "2. Speak to Rumpelstinskin.\n\n"],
    "chapter1_cont": ["Snow decides to speak to Rumpel.\n",
                      "Upon the visit, Rumpel explains\n",
                      "that the only way to save them \n",
                      "all was to hide Snow White in a magical wardrobe \n",
                      "so she could be transported to the unknown land. \n",
                      "However, there was a condition attached. \n",
                      "Rumpel asked for the baby’s name:\n\n",
                      "1. Snow decides to tell the baby’s name.\n",
                      "2. Snow does not disclose the name.\n\n"],
    "chapter2": ["Chapter 2\n",
                 "On the day of the planned escape, a purple curse cloud \n",
                 "arose…The Queen’s Army has stormed the Castle, \n",
                 "forcing Snow and Prince to rush to the wardrobe. \n",
                 "Alas their baby decided to come.\n\n",
                 "The army is at the end of the corridor. \n",
                 "Should Snow and Charming:\n\n",
                 "1. Fight the Queen's army.\n",
                 "2. Escape through the secret door.\n\n"],
    "chapter2_cont": ["They run down the secret stairs a level below where \n",
                      "the wardrobe room is located. Snow and Charming are \n",
                      "noticed by a soldier and starts \n",
                      "marching their way:\n\n",
                      "1. Charming fights the soldier.\n",
                      "2. Charming locks the door.\n\n"],
    "chapter2_cont2": ["The soldier is behind the door trying to break in. \n",
                       "Snow and the baby steps into the wardrobe but it \n",
                       "does not work. The soldier manages to break \n",
                       "through the door: \n\n",
                       "1. Snow places the baby in the wardrobe.\n",
                       "2. Charming fights the soldier.\n\n"],
    "chapter2_cont3": ["The curse is released and the fairytale characters \n",
                       "find themselves in StoryBrooke, where they are \n",
                       "stripped of their memories and living \n",
                       "hapless lives, while the Queen revels in her \n",
                       "accomplishment.\n\n",
                       "But hope is not lost, as {emma} has managed \n",
                       "to escape. Will the curse be broken?\n"]
}
